scan_timeout = 10

add_newline = true
right_format = """$cmd_duration"""

[line_break]
disabled=false

[character]
error_symbol = "[âœ—](bold red) "

[cmd_duration]
show_milliseconds=true
show_notifications=true
min_time_to_notify=45_000
format = '[ â±  $duration]($style)'
style="yellow"

[aws]
symbol = "îŒ½  "
disabled = true

[buf]
symbol = "ï’ "

[conda]
symbol = "ï„Œ "

[dart]
 symbol = "î˜ "

[directory]
read_only = " ï ½"
truncation_symbol = "â€¦/"

[gcloud]
disabled=true

[java]
symbol = "î‰– "

[kubernetes]
disabled=true

[status]
style = "red"
symbol = "âœ— "
map_symbol = true
success_symbol = ""
format = '[$symbol$common_meaning$signal_name$maybe_int]($style) '
disabled = true


[docker_context]
symbol = "ïŒˆ "

[elixir]
symbol = "î‰µ "

[elm]
symbol = "î˜¬ "

[git_branch]
symbol = "ï˜ "
format="[\\[$symbol$branch\\]]($style) "
style="fg:#bf5700" 
#ignore_branches = ["master", "main"]

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[ğŸ’ PICKING](bold red)"

[git_status]
up_to_date = "âœ“ "
deleted = "x"
staged = '[++\($count\)](green)'
ahead = "â‡¡${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
behind = "â‡£${count}"
style="fg:#bf5700" 

[golang]
symbol = "î˜§ "

[haskell]
symbol = "î· "

[hg_branch]
symbol = "ï˜ "

[julia]
symbol = "î˜¤ "

[memory_usage]
symbol = "ï¡š "

[nim]
symbol = "ïš¤ "

[nix_shell]
symbol = "ï‹œ "

[nodejs]
#symbol = "îœ˜"
symbol = "ğŸ¤– "
format="[\\[$symbol($version)\\]]($style)"
style="green"

[package]
symbol = "ï£– "

[rust]
symbol = "î¨ "
